listen_addresses = '*'
max_connections = 50

shared_buffers = 128MB
effective_cache_size = 385MB
work_mem = 2MB
maintenance_work_mem = 32MB

wal_buffers = 4MB
checkpoint_completion_target = 0.9
wal_compression = on
min_wal_size = 128MB
max_wal_size = 1GB

log_destination = 'stderr'
logging_collector = off
log_min_messages = warning
log_min_error_statement = error
log_min_duration_statement = 1000

ssl = off
password_encryption = scram-sha-256

random_page_cost = 1.1
effective_io_concurrency = 2
